export const DOC_VIEW_STATES = Object.freeze({
  BOOTSTRAPPING: 'bootstrapping',
  LOADING_READ: 'loading-read',
  LOADING_EDIT: 'loading-edit',
  READY_READ: 'ready-read',
  READY_EDIT: 'ready-edit',
  LOAD_ERROR: 'load-error',
});

export const DOC_VIEW_TRANSITIONS = Object.freeze({
  [DOC_VIEW_STATES.BOOTSTRAPPING]: {
    START_READ: DOC_VIEW_STATES.LOADING_READ,
    START_EDIT: DOC_VIEW_STATES.LOADING_EDIT,
  },
  [DOC_VIEW_STATES.LOADING_READ]: {
    SET_EDIT: DOC_VIEW_STATES.LOADING_EDIT,
    MARK_READY: DOC_VIEW_STATES.READY_READ,
    MARK_FAILED: DOC_VIEW_STATES.LOAD_ERROR,
  },
  [DOC_VIEW_STATES.LOADING_EDIT]: {
    SET_READ: DOC_VIEW_STATES.LOADING_READ,
    MARK_READY: DOC_VIEW_STATES.READY_EDIT,
    MARK_FAILED: DOC_VIEW_STATES.LOAD_ERROR,
  },
  [DOC_VIEW_STATES.READY_READ]: {
    SET_EDIT: DOC_VIEW_STATES.READY_EDIT,
    RELOAD_READ: DOC_VIEW_STATES.LOADING_READ,
    RELOAD_EDIT: DOC_VIEW_STATES.LOADING_EDIT,
    MARK_FAILED: DOC_VIEW_STATES.LOAD_ERROR,
  },
  [DOC_VIEW_STATES.READY_EDIT]: {
    SET_READ: DOC_VIEW_STATES.READY_READ,
    RELOAD_READ: DOC_VIEW_STATES.LOADING_READ,
    RELOAD_EDIT: DOC_VIEW_STATES.LOADING_EDIT,
    MARK_FAILED: DOC_VIEW_STATES.LOAD_ERROR,
  },
  [DOC_VIEW_STATES.LOAD_ERROR]: {
    START_READ: DOC_VIEW_STATES.LOADING_READ,
    START_EDIT: DOC_VIEW_STATES.LOADING_EDIT,
  },
});

export const DOC_SAVE_STATES = Object.freeze({
  IDLE: 'idle',
  DIRTY: 'dirty',
  SAVING: 'saving',
  SAVED: 'saved',
  ERROR: 'error',
});

export const DOC_SAVE_TRANSITIONS = Object.freeze({
  [DOC_SAVE_STATES.IDLE]: {
    MARK_DIRTY: DOC_SAVE_STATES.DIRTY,
    START_SAVE: DOC_SAVE_STATES.SAVING,
    SYNC_CLEAN: DOC_SAVE_STATES.IDLE,
  },
  [DOC_SAVE_STATES.DIRTY]: {
    MARK_DIRTY: DOC_SAVE_STATES.DIRTY,
    START_SAVE: DOC_SAVE_STATES.SAVING,
    SYNC_CLEAN: DOC_SAVE_STATES.IDLE,
  },
  [DOC_SAVE_STATES.SAVING]: {
    MARK_DIRTY: DOC_SAVE_STATES.DIRTY,
    SAVE_COMPLETE: DOC_SAVE_STATES.SAVED,
    SAVE_FAILED: DOC_SAVE_STATES.ERROR,
  },
  [DOC_SAVE_STATES.SAVED]: {
    MARK_DIRTY: DOC_SAVE_STATES.DIRTY,
    START_SAVE: DOC_SAVE_STATES.SAVING,
    CLEAR_SAVED: DOC_SAVE_STATES.IDLE,
    SYNC_CLEAN: DOC_SAVE_STATES.IDLE,
  },
  [DOC_SAVE_STATES.ERROR]: {
    MARK_DIRTY: DOC_SAVE_STATES.DIRTY,
    START_SAVE: DOC_SAVE_STATES.SAVING,
    SYNC_CLEAN: DOC_SAVE_STATES.IDLE,
  },
});